language: python
python:
- '2.7'
branches:
  only:
  - master
  - stage
before_install:
- sudo apt-get -qq update
install: pip install -r requirements.txt
addons:
  postgresql: '9.4'
services:
- postgresql
before_script:
- psql -c 'create database demo_db;' -U postgres
script: nosetests
deploy:
  provider: s3
  access_key_id: "AKIAI24XBD5GSZ2L3GHQ"
  secret_access_key:
    secure: "lZI7eMIV0AQfCntRNd+vCZyUs35PzMlyRcAE/1/IU8p0j6V5JBSn9LetZmqUPRvmlo8Gesg8jpx0Rofr2WjChD8qG1BjN44V+/jBcFzXd9dVJ81M5B+2cz4ICI8O0dp3rlnfJkYMkJe4LOsUvENR94DsvVo+jFPfqyk+naaWPH7pIYWPfJwhu0aJo7/igtgnpoWvZZlswCnQ4TmljIh2mo7hVLJCsQKvh3ZN9kJpXSbKm3IG4vqXCTfZqoa4v9Or9tRcm02DFg3Il4AJLXfMTQQEY2QGeHQs6MuJ9zVkEH7xtq5qIGYcD+JiJdEJ0TZTuuxRvGPSopvzKe5mBg2U5F8Z9rHFaOp2ya51zOqrdyLm6A/rJ2ApHkZYfYa62dP1IR72JdUG6vKR0qLnrdIE6xfI7bgB1Jrlhg0fSfZTAI+pl+XpBCA4lOJl1erTz5OrW+ue9U6NddYjXOM4RY4fVNQGTOvER5zlVpLsNp+YqzVPS85xMGRII48aJgqpL9C8IQtscf2WeuPvH6UiDw3hoB74hG2/H4JI5F1jrpAQMO+lPdHfRbmhTnb2uxJIC+aIra+hE2szBG/aR1pxKSXkbp8LqfsLXNfvUUDdlvA4opK1YEEAC8toB6vEA7/JzW631CSOlB818+QvyZksXRWPIatYKRNV9i6rvVPAHMwEArA="
  bucket: "appen-file-upload-example-20150622"
  skip_cleanup: true
  region: ap-southeast-2
